# Generated by Django 3.2.5 on 2021-07-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images')),
                ('main_title', models.CharField(max_length=250)),
                ('top_title', models.CharField(max_length=250)),
                ('bottom_title', models.CharField(max_length=250)),
                ('is_slider', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=10, verbose_name='Slider olsun mu?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliderlar',
                'db_table': 'slider',
            },
        ),
    ]
