# Generated by Django 3.2.5 on 2021-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimBilgilerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konum', models.CharField(max_length=250)),
                ('telefon', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'İletişim Bilgileri',
                'verbose_name_plural': 'İletişim Bilgilerimiz',
                'db_table': 'IletisimBilgiler',
            },
        ),
    ]
