# Generated by Django 3.2.5 on 2021-07-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_iletisimbilgilermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('okundu_mu', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=10, verbose_name='Okundu mu?')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Gelen Mesajlar',
                'db_table': 'IletisimModel',
            },
        ),
    ]
