# Generated by Django 3.2.5 on 2021-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0004_hakkimizdamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('yazi', models.TextField(max_length=200)),
                ('tarih', models.CharField(max_length=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zaman Çizelgesi',
                'verbose_name_plural': 'Zaman Çizelgeleri',
                'db_table': 'TimelineModel',
            },
        ),
    ]
