# Generated by Django 3.2.5 on 2021-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0005_timelinemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvukatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alan', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='avukat_images')),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avukat',
                'verbose_name_plural': 'Avukatlar',
                'db_table': 'AvukatModel',
            },
        ),
    ]
