# Generated by Django 3.2.5 on 2021-07-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0006_avukatmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Çalışma Alanı',
                'verbose_name_plural': 'Çalışma Alanları',
                'db_table': 'AlanModel',
            },
        ),
    ]
