# Generated by Django 3.2.5 on 2021-08-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0007_alanmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NedenBizModeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Neden Bizi Seçmelisiniz?',
                'verbose_name_plural': 'Neden Biz',
                'db_table': 'NedenBizModeli',
            },
        ),
    ]
