# Generated by Django 3.2.5 on 2021-08-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0009_nedenbizmodeli_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nedenbizmodeli',
            name='image',
        ),
    ]
