# Generated by Django 3.2.5 on 2021-08-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0010_remove_nedenbizmodeli_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NedenBizImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nedenbiz_image')),
            ],
            options={
                'verbose_name': 'Neden Biz Fotoğraf',
                'verbose_name_plural': 'Neden Biz Fotosu',
                'db_table': 'NedenBizImageModel',
            },
        ),
    ]
