# Generated by Django 3.2.5 on 2021-08-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0011_nedenbizimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizdamodel',
            name='image_single',
            field=models.ImageField(default='', upload_to='hakkimizda_images'),
        ),
    ]
