# Generated by Django 3.2.5 on 2021-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0016_auto_20210802_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimbilgilermodel',
            name='facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iletisimbilgilermodel',
            name='instagram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iletisimbilgilermodel',
            name='linkedin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iletisimbilgilermodel',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
    ]
