# Generated by Django 3.2.5 on 2021-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0017_auto_20210802_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimbilgilermodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iletisimbilgilermodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iletisimbilgilermodel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
