# Generated by Django 3.2.5 on 2021-08-03 07:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0019_reviewmodel_sorumodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=ckeditor.fields.RichTextField(max_length=150),
        ),
    ]
